var annotated_dup =
[
    [ "address", "namespaceaddress.html", [
      [ "comp_bot", "namespaceaddress_1_1comp__bot.html", [
        [ "climber", "structaddress_1_1comp__bot_1_1climber.html", "structaddress_1_1comp__bot_1_1climber" ],
        [ "controllers", "structaddress_1_1comp__bot_1_1controllers.html", "structaddress_1_1comp__bot_1_1controllers" ],
        [ "drive", "structaddress_1_1comp__bot_1_1drive.html", "structaddress_1_1comp__bot_1_1drive" ],
        [ "elevator", "structaddress_1_1comp__bot_1_1elevator.html", "structaddress_1_1comp__bot_1_1elevator" ],
        [ "encoders", "structaddress_1_1comp__bot_1_1encoders.html", "structaddress_1_1comp__bot_1_1encoders" ],
        [ "intake", "structaddress_1_1comp__bot_1_1intake.html", "structaddress_1_1comp__bot_1_1intake" ],
        [ "led", "structaddress_1_1comp__bot_1_1led.html", "structaddress_1_1comp__bot_1_1led" ],
        [ "sensors", "structaddress_1_1comp__bot_1_1sensors.html", "structaddress_1_1comp__bot_1_1sensors" ],
        [ "solenoids", "structaddress_1_1comp__bot_1_1solenoids.html", null ]
      ] ]
    ] ],
    [ "argos_lib", "namespaceargos__lib.html", [
      [ "cancoder_config", "namespaceargos__lib_1_1cancoder__config.html", [
        [ "has_absoluteSensorDiscontinuityPoint", "structargos__lib_1_1cancoder__config_1_1has__absolute_sensor_discontinuity_point.html", null ],
        [ "has_absoluteSensorDiscontinuityPoint< T, decltype((void) T::absoluteSensorDiscontinuityPoint, void())>", "structargos__lib_1_1cancoder__config_1_1has__absolute_sensor_discontinuity_point_3_01_t_00_01dec4ad6993d4013c71e6ebc81d222b9a6ef.html", null ],
        [ "has_direction", "structargos__lib_1_1cancoder__config_1_1has__direction.html", null ],
        [ "has_direction< T, decltype((void) T::direction, void())>", "structargos__lib_1_1cancoder__config_1_1has__direction_3_01_t_00_01decltype_07_07void_08_01_t_1_1direction_00_01void_07_08_08_4.html", null ],
        [ "has_magOffset", "structargos__lib_1_1cancoder__config_1_1has__mag_offset.html", null ],
        [ "has_magOffset< T, decltype((void) T::magOffset, void())>", "structargos__lib_1_1cancoder__config_1_1has__mag_offset_3_01_t_00_01decltype_07_07void_08_01_t_1de2a467e5a7d6bbfd81fd01645e37d7d.html", null ]
      ] ],
      [ "falcon_config", "namespaceargos__lib_1_1falcon__config.html", [
        [ "has_dutyCycleNeutralDeadband", "structargos__lib_1_1falcon__config_1_1has__duty_cycle_neutral_deadband.html", null ],
        [ "has_dutyCycleNeutralDeadband< T, decltype((void) T::dutyCycleNeutralDeadband, void())>", "structargos__lib_1_1falcon__config_1_1has__duty_cycle_neutral_deadband_3_01_t_00_01decltype_07_010b31c329ff492e1832d52316d7cd13f.html", null ],
        [ "has_dutyCycleOpenLoopRampPeriod", "structargos__lib_1_1falcon__config_1_1has__duty_cycle_open_loop_ramp_period.html", null ],
        [ "has_dutyCycleOpenLoopRampPeriod< T, decltype((void) T::dutyCycleOpenLoopRampPeriod, void())>", "structargos__lib_1_1falcon__config_1_1has__duty_cycle_open_loop_ramp_period_3_01_t_00_01decltype4e85b3988be8fcd5099848b351340e43.html", null ],
        [ "has_forwardLimit_deviceID", "structargos__lib_1_1falcon__config_1_1has__forward_limit__device_i_d.html", null ],
        [ "has_forwardLimit_deviceID< T, decltype((void) T::forwardLimit_deviceID, void())>", "structargos__lib_1_1falcon__config_1_1has__forward_limit__device_i_d_3_01_t_00_01decltype_07_07v44ebeb962e49a9b1f260a076090b52d3.html", null ],
        [ "has_forwardLimit_normalState", "structargos__lib_1_1falcon__config_1_1has__forward_limit__normal_state.html", null ],
        [ "has_forwardLimit_normalState< T, decltype((void) T::forwardLimit_normalState, void())>", "structargos__lib_1_1falcon__config_1_1has__forward_limit__normal_state_3_01_t_00_01decltype_07_0ecc9d7a2c7e7d191f194154e369f1861.html", null ],
        [ "has_forwardLimit_source", "structargos__lib_1_1falcon__config_1_1has__forward_limit__source.html", null ],
        [ "has_forwardLimit_source< T, decltype((void) T::forwardLimit_source, void())>", "structargos__lib_1_1falcon__config_1_1has__forward_limit__source_3_01_t_00_01decltype_07_07void_81fab8e5132e69108d2fa80a116df1a2.html", null ],
        [ "has_inverted", "structargos__lib_1_1falcon__config_1_1has__inverted.html", null ],
        [ "has_inverted< T, decltype((void) T::inverted, void())>", "structargos__lib_1_1falcon__config_1_1has__inverted_3_01_t_00_01decltype_07_07void_08_01_t_1_1inverted_00_01void_07_08_08_4.html", null ],
        [ "has_motionMagic_acceleration", "structargos__lib_1_1falcon__config_1_1has__motion_magic__acceleration.html", null ],
        [ "has_motionMagic_acceleration< T, decltype((void) T::motionMagic_acceleration, void())>", "structargos__lib_1_1falcon__config_1_1has__motion_magic__acceleration_3_01_t_00_01decltype_07_0760299ea40322f0fe6ea0e1bcbc64d13c.html", null ],
        [ "has_motionMagic_cruiseVelocity", "structargos__lib_1_1falcon__config_1_1has__motion_magic__cruise_velocity.html", null ],
        [ "has_motionMagic_cruiseVelocity< T, decltype((void) T::motionMagic_cruiseVelocity, void())>", "structargos__lib_1_1falcon__config_1_1has__motion_magic__cruise_velocity_3_01_t_00_01decltype_0753ee5bc1f3b50368d81965eabcc06350.html", null ],
        [ "has_motionMagic_expo_kA", "structargos__lib_1_1falcon__config_1_1has__motion_magic__expo__k_a.html", null ],
        [ "has_motionMagic_expo_kA< T, decltype((void) T::motionMagic_expo_kA, void())>", "structargos__lib_1_1falcon__config_1_1has__motion_magic__expo__k_a_3_01_t_00_01decltype_07_07voiceb4d986109c612dbbc8612117baf439.html", null ],
        [ "has_motionMagic_expo_kV", "structargos__lib_1_1falcon__config_1_1has__motion_magic__expo__k_v.html", null ],
        [ "has_motionMagic_expo_kV< T, decltype((void) T::motionMagic_expo_kV, void())>", "structargos__lib_1_1falcon__config_1_1has__motion_magic__expo__k_v_3_01_t_00_01decltype_07_07voieb9e93afe61c046024285df05a2b4232.html", null ],
        [ "has_motionMagic_jerk", "structargos__lib_1_1falcon__config_1_1has__motion_magic__jerk.html", null ],
        [ "has_motionMagic_jerk< T, decltype((void) T::motionMagic_jerk, void())>", "structargos__lib_1_1falcon__config_1_1has__motion_magic__jerk_3_01_t_00_01decltype_07_07void_08_438ad055a0ffdbd8522c01f581590408.html", null ],
        [ "has_neutralDeadband", "structargos__lib_1_1falcon__config_1_1has__neutral_deadband.html", null ],
        [ "has_neutralDeadband< T, decltype((void) T::neutralDeadband, void())>", "structargos__lib_1_1falcon__config_1_1has__neutral_deadband_3_01_t_00_01decltype_07_07void_08_015c25ddef8ee00d07f9e2181984886a62.html", null ],
        [ "has_neutralMode", "structargos__lib_1_1falcon__config_1_1has__neutral_mode.html", null ],
        [ "has_neutralMode< T, decltype((void) T::neutralMode, void())>", "structargos__lib_1_1falcon__config_1_1has__neutral_mode_3_01_t_00_01decltype_07_07void_08_01_t_1620830597d5b98976bd82c381d419920.html", null ],
        [ "has_nominalOutputForward", "structargos__lib_1_1falcon__config_1_1has__nominal_output_forward.html", null ],
        [ "has_nominalOutputForward< T, decltype((void) T::nominalOutputForward, void())>", "structargos__lib_1_1falcon__config_1_1has__nominal_output_forward_3_01_t_00_01decltype_07_07void7113e9ec65b94cdb6e5292363b4ddc27.html", null ],
        [ "has_nominalOutputReverse", "structargos__lib_1_1falcon__config_1_1has__nominal_output_reverse.html", null ],
        [ "has_nominalOutputReverse< T, decltype((void) T::nominalOutputReverse, void())>", "structargos__lib_1_1falcon__config_1_1has__nominal_output_reverse_3_01_t_00_01decltype_07_07voidb67916fd1c718b24ddeefec63ee3d08d.html", null ],
        [ "has_peakOutputForward", "structargos__lib_1_1falcon__config_1_1has__peak_output_forward.html", null ],
        [ "has_peakOutputForward< T, decltype((void) T::peakOutputForward, void())>", "structargos__lib_1_1falcon__config_1_1has__peak_output_forward_3_01_t_00_01decltype_07_07void_08f9925878016540efcc21a0f90f55af80.html", null ],
        [ "has_peakOutputReverse", "structargos__lib_1_1falcon__config_1_1has__peak_output_reverse.html", null ],
        [ "has_peakOutputReverse< T, decltype((void) T::peakOutputReverse, void())>", "structargos__lib_1_1falcon__config_1_1has__peak_output_reverse_3_01_t_00_01decltype_07_07void_0814bc5bcb4c61a1ac948dffcbdc9dea51.html", null ],
        [ "has_pid0_gravityType", "structargos__lib_1_1falcon__config_1_1has__pid0__gravity_type.html", null ],
        [ "has_pid0_gravityType< T, decltype((void) T::pid0_gravityType, void())>", "structargos__lib_1_1falcon__config_1_1has__pid0__gravity_type_3_01_t_00_01decltype_07_07void_08_7be28771b6a25ce1c47c08e644de5dc1.html", null ],
        [ "has_pid0_kA", "structargos__lib_1_1falcon__config_1_1has__pid0__k_a.html", null ],
        [ "has_pid0_kA< T, decltype((void) T::pid0_kA, void())>", "structargos__lib_1_1falcon__config_1_1has__pid0__k_a_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_a_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_kD", "structargos__lib_1_1falcon__config_1_1has__pid0__k_d.html", null ],
        [ "has_pid0_kD< T, decltype((void) T::pid0_kD, void())>", "structargos__lib_1_1falcon__config_1_1has__pid0__k_d_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_d_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_kG", "structargos__lib_1_1falcon__config_1_1has__pid0__k_g.html", null ],
        [ "has_pid0_kG< T, decltype((void) T::pid0_kG, void())>", "structargos__lib_1_1falcon__config_1_1has__pid0__k_g_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_g_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_kI", "structargos__lib_1_1falcon__config_1_1has__pid0__k_i.html", null ],
        [ "has_pid0_kI< T, decltype((void) T::pid0_kI, void())>", "structargos__lib_1_1falcon__config_1_1has__pid0__k_i_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_i_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_kP", "structargos__lib_1_1falcon__config_1_1has__pid0__k_p.html", null ],
        [ "has_pid0_kP< T, decltype((void) T::pid0_kP, void())>", "structargos__lib_1_1falcon__config_1_1has__pid0__k_p_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_p_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_kS", "structargos__lib_1_1falcon__config_1_1has__pid0__k_s.html", null ],
        [ "has_pid0_kS< T, decltype((void) T::pid0_kS, void())>", "structargos__lib_1_1falcon__config_1_1has__pid0__k_s_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_s_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_kV", "structargos__lib_1_1falcon__config_1_1has__pid0__k_v.html", null ],
        [ "has_pid0_kV< T, decltype((void) T::pid0_kV, void())>", "structargos__lib_1_1falcon__config_1_1has__pid0__k_v_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_v_00_01void_07_08_08_4.html", null ],
        [ "has_pid1_gravityType", "structargos__lib_1_1falcon__config_1_1has__pid1__gravity_type.html", null ],
        [ "has_pid1_gravityType< T, decltype((void) T::pid1_gravityType, void())>", "structargos__lib_1_1falcon__config_1_1has__pid1__gravity_type_3_01_t_00_01decltype_07_07void_08_21686b5f2ee4a231c1132b7571029c3e.html", null ],
        [ "has_pid1_kA", "structargos__lib_1_1falcon__config_1_1has__pid1__k_a.html", null ],
        [ "has_pid1_kA< T, decltype((void) T::pid1_kA, void())>", "structargos__lib_1_1falcon__config_1_1has__pid1__k_a_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid1__k_a_00_01void_07_08_08_4.html", null ],
        [ "has_pid1_kD", "structargos__lib_1_1falcon__config_1_1has__pid1__k_d.html", null ],
        [ "has_pid1_kD< T, decltype((void) T::pid1_kD, void())>", "structargos__lib_1_1falcon__config_1_1has__pid1__k_d_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid1__k_d_00_01void_07_08_08_4.html", null ],
        [ "has_pid1_kG", "structargos__lib_1_1falcon__config_1_1has__pid1__k_g.html", null ],
        [ "has_pid1_kG< T, decltype((void) T::pid1_kG, void())>", "structargos__lib_1_1falcon__config_1_1has__pid1__k_g_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid1__k_g_00_01void_07_08_08_4.html", null ],
        [ "has_pid1_kI", "structargos__lib_1_1falcon__config_1_1has__pid1__k_i.html", null ],
        [ "has_pid1_kI< T, decltype((void) T::pid1_kI, void())>", "structargos__lib_1_1falcon__config_1_1has__pid1__k_i_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid1__k_i_00_01void_07_08_08_4.html", null ],
        [ "has_pid1_kP", "structargos__lib_1_1falcon__config_1_1has__pid1__k_p.html", null ],
        [ "has_pid1_kP< T, decltype((void) T::pid1_kP, void())>", "structargos__lib_1_1falcon__config_1_1has__pid1__k_p_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid1__k_p_00_01void_07_08_08_4.html", null ],
        [ "has_pid1_kS", "structargos__lib_1_1falcon__config_1_1has__pid1__k_s.html", null ],
        [ "has_pid1_kS< T, decltype((void) T::pid1_kS, void())>", "structargos__lib_1_1falcon__config_1_1has__pid1__k_s_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid1__k_s_00_01void_07_08_08_4.html", null ],
        [ "has_pid1_kV", "structargos__lib_1_1falcon__config_1_1has__pid1__k_v.html", null ],
        [ "has_pid1_kV< T, decltype((void) T::pid1_kV, void())>", "structargos__lib_1_1falcon__config_1_1has__pid1__k_v_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid1__k_v_00_01void_07_08_08_4.html", null ],
        [ "has_reverseLimit_deviceID", "structargos__lib_1_1falcon__config_1_1has__reverse_limit__device_i_d.html", null ],
        [ "has_reverseLimit_deviceID< T, decltype((void) T::reverseLimit_deviceID, void())>", "structargos__lib_1_1falcon__config_1_1has__reverse_limit__device_i_d_3_01_t_00_01decltype_07_07vf68ebe355f714defcc74df12f0fc3e07.html", null ],
        [ "has_reverseLimit_normalState", "structargos__lib_1_1falcon__config_1_1has__reverse_limit__normal_state.html", null ],
        [ "has_reverseLimit_normalState< T, decltype((void) T::reverseLimit_normalState, void())>", "structargos__lib_1_1falcon__config_1_1has__reverse_limit__normal_state_3_01_t_00_01decltype_07_0a382814b0f38b30f034d150cee564e44.html", null ],
        [ "has_reverseLimit_source", "structargos__lib_1_1falcon__config_1_1has__reverse_limit__source.html", null ],
        [ "has_reverseLimit_source< T, decltype((void) T::reverseLimit_source, void())>", "structargos__lib_1_1falcon__config_1_1has__reverse_limit__source_3_01_t_00_01decltype_07_07void_44a515af1f068a9815bdd41ed603153d.html", null ],
        [ "has_rotorToSensorRatio", "structargos__lib_1_1falcon__config_1_1has__rotor_to_sensor_ratio.html", null ],
        [ "has_rotorToSensorRatio< T, decltype((void) T::rotorToSensorRatio, void())>", "structargos__lib_1_1falcon__config_1_1has__rotor_to_sensor_ratio_3_01_t_00_01decltype_07_07void_1dbf77541d42027610433659fe455129.html", null ],
        [ "has_selectedSensor", "structargos__lib_1_1falcon__config_1_1has__selected_sensor.html", null ],
        [ "has_selectedSensor< T, decltype((void) T::selectedSensor, void())>", "structargos__lib_1_1falcon__config_1_1has__selected_sensor_3_01_t_00_01decltype_07_07void_08_01_4399fb92f062b32c4520d4faa3354800.html", null ],
        [ "has_selectedSensor_addr", "structargos__lib_1_1falcon__config_1_1has__selected_sensor__addr.html", null ],
        [ "has_selectedSensor_addr< T, decltype((void) T::selectedSensor_addr, void())>", "structargos__lib_1_1falcon__config_1_1has__selected_sensor__addr_3_01_t_00_01decltype_07_07void_469288264d9bf2db7d8483223a0e32e4.html", null ],
        [ "has_sensorToMechanismRatio", "structargos__lib_1_1falcon__config_1_1has__sensor_to_mechanism_ratio.html", null ],
        [ "has_sensorToMechanismRatio< T, decltype((void) T::sensorToMechanismRatio, void())>", "structargos__lib_1_1falcon__config_1_1has__sensor_to_mechanism_ratio_3_01_t_00_01decltype_07_07vcea878ee792e73b5a575b388fa007392.html", null ],
        [ "has_statorCurrentLimit", "structargos__lib_1_1falcon__config_1_1has__stator_current_limit.html", null ],
        [ "has_statorCurrentLimit< T, decltype((void) T::statorCurrentLimit, void())>", "structargos__lib_1_1falcon__config_1_1has__stator_current_limit_3_01_t_00_01decltype_07_07void_0725b44c65551ddaf62c0e4bea0e8192b.html", null ],
        [ "has_statusFrameMotorMode", "structargos__lib_1_1falcon__config_1_1has__status_frame_motor_mode.html", null ],
        [ "has_statusFrameMotorMode< T, decltype((void) T::statusFrameMotorMode, void())>", "structargos__lib_1_1falcon__config_1_1has__status_frame_motor_mode_3_01_t_00_01decltype_07_07voi2f2717a3e49b6fdffa076fad9d7a7425.html", null ],
        [ "has_supplyCurrentLimit", "structargos__lib_1_1falcon__config_1_1has__supply_current_limit.html", null ],
        [ "has_supplyCurrentLimit< T, decltype((void) T::supplyCurrentLimit, void())>", "structargos__lib_1_1falcon__config_1_1has__supply_current_limit_3_01_t_00_01decltype_07_07void_012cda0473719e58ee24f06eba96a52ba.html", null ],
        [ "has_supplyCurrentLowerLimit", "structargos__lib_1_1falcon__config_1_1has__supply_current_lower_limit.html", null ],
        [ "has_supplyCurrentLowerLimit< T, decltype((void) T::supplyCurrentLowerLimit, void())>", "structargos__lib_1_1falcon__config_1_1has__supply_current_lower_limit_3_01_t_00_01decltype_07_07716e0bbb4b109d81dec8259d50e4e4a2.html", null ],
        [ "has_supplyCurrentLowerTime", "structargos__lib_1_1falcon__config_1_1has__supply_current_lower_time.html", null ],
        [ "has_supplyCurrentLowerTime< T, decltype((void) T::supplyCurrentLowerTime, void())>", "structargos__lib_1_1falcon__config_1_1has__supply_current_lower_time_3_01_t_00_01decltype_07_07v485efd48d4364c6af3620f4106fe8e39.html", null ],
        [ "has_voltageOpenLoopRampPeriod", "structargos__lib_1_1falcon__config_1_1has__voltage_open_loop_ramp_period.html", null ],
        [ "has_voltageOpenLoopRampPeriod< T, decltype((void) T::voltageOpenLoopRampPeriod, void())>", "structargos__lib_1_1falcon__config_1_1has__voltage_open_loop_ramp_period_3_01_t_00_01decltype_07e819fc579ee2ca0681fe2a1e7f22ebf9.html", null ]
      ] ],
      [ "led", "namespaceargos__lib_1_1led.html", [
        [ "Animation", "structargos__lib_1_1led_1_1_animation.html", "structargos__lib_1_1led_1_1_animation" ],
        [ "Array2D", "classargos__lib_1_1led_1_1_array2_d.html", "classargos__lib_1_1led_1_1_array2_d" ],
        [ "PanelScanParams", "structargos__lib_1_1led_1_1_panel_scan_params.html", "structargos__lib_1_1led_1_1_panel_scan_params" ],
        [ "Sprite", "structargos__lib_1_1led_1_1_sprite.html", "structargos__lib_1_1led_1_1_sprite" ]
      ] ],
      [ "swerve", "namespaceargos__lib_1_1swerve.html", [
        [ "NetworkTablesHomingStorage", "classargos__lib_1_1swerve_1_1_network_tables_homing_storage.html", "classargos__lib_1_1swerve_1_1_network_tables_homing_storage" ],
        [ "SwerveModulePositions", "structargos__lib_1_1swerve_1_1_swerve_module_positions.html", "structargos__lib_1_1swerve_1_1_swerve_module_positions" ],
        [ "TranslationSpeeds", "structargos__lib_1_1swerve_1_1_translation_speeds.html", "structargos__lib_1_1swerve_1_1_translation_speeds" ]
      ] ],
      [ "talonsrx_config", "namespaceargos__lib_1_1talonsrx__config.html", [
        [ "has_continuousCurrentLimit", "structargos__lib_1_1talonsrx__config_1_1has__continuous_current_limit.html", null ],
        [ "has_continuousCurrentLimit< T, decltype((void) T::continuousCurrentLimit, void())>", "structargos__lib_1_1talonsrx__config_1_1has__continuous_current_limit_3_01_t_00_01decltype_07_07e9620060a5cb4766114183f43e7a3c15.html", null ],
        [ "has_forwardLimitSwitchNormal", "structargos__lib_1_1talonsrx__config_1_1has__forward_limit_switch_normal.html", null ],
        [ "has_forwardLimitSwitchNormal< T, decltype((void) T::forwardLimitSwitchNormal, void())>", "structargos__lib_1_1talonsrx__config_1_1has__forward_limit_switch_normal_3_01_t_00_01decltype_07c002224cd862ad1baf2e3ae426710ccc.html", null ],
        [ "has_forwardLimitSwitchSource", "structargos__lib_1_1talonsrx__config_1_1has__forward_limit_switch_source.html", null ],
        [ "has_forwardLimitSwitchSource< T, decltype((void) T::forwardLimitSwitchSource, void())>", "structargos__lib_1_1talonsrx__config_1_1has__forward_limit_switch_source_3_01_t_00_01decltype_0774c486286bcb4d22c579262d641d9193.html", null ],
        [ "has_inverted", "structargos__lib_1_1talonsrx__config_1_1has__inverted.html", null ],
        [ "has_inverted< T, decltype((void) T::inverted, void())>", "structargos__lib_1_1talonsrx__config_1_1has__inverted_3_01_t_00_01decltype_07_07void_08_01_t_1_1inverted_00_01void_07_08_08_4.html", null ],
        [ "has_neutralMode", "structargos__lib_1_1talonsrx__config_1_1has__neutral_mode.html", null ],
        [ "has_neutralMode< T, decltype((void) T::neutralMode, void())>", "structargos__lib_1_1talonsrx__config_1_1has__neutral_mode_3_01_t_00_01decltype_07_07void_08_01_t835aaf6e014b6e63da745c895a8c0b11.html", null ],
        [ "has_peakCurrentDuration", "structargos__lib_1_1talonsrx__config_1_1has__peak_current_duration.html", null ],
        [ "has_peakCurrentDuration< T, decltype((void) T::peakCurrentDuration, void())>", "structargos__lib_1_1talonsrx__config_1_1has__peak_current_duration_3_01_t_00_01decltype_07_07voi2457400402699398aaa153781132c408.html", null ],
        [ "has_peakCurrentLimit", "structargos__lib_1_1talonsrx__config_1_1has__peak_current_limit.html", null ],
        [ "has_peakCurrentLimit< T, decltype((void) T::peakCurrentLimit, void())>", "structargos__lib_1_1talonsrx__config_1_1has__peak_current_limit_3_01_t_00_01decltype_07_07void_0db8907e3ba67f8de3b90a48d5759ccf8.html", null ],
        [ "has_peakOutputForward", "structargos__lib_1_1talonsrx__config_1_1has__peak_output_forward.html", null ],
        [ "has_peakOutputForward< T, decltype((void) T::peakOutputForward, void())>", "structargos__lib_1_1talonsrx__config_1_1has__peak_output_forward_3_01_t_00_01decltype_07_07void_ce1393e4ba3aff645158e2468cf2e124.html", null ],
        [ "has_peakOutputReverse", "structargos__lib_1_1talonsrx__config_1_1has__peak_output_reverse.html", null ],
        [ "has_peakOutputReverse< T, decltype((void) T::peakOutputReverse, void())>", "structargos__lib_1_1talonsrx__config_1_1has__peak_output_reverse_3_01_t_00_01decltype_07_07void_073517f0314ac977e5b02011a3d9b917.html", null ],
        [ "has_pid0_allowableError", "structargos__lib_1_1talonsrx__config_1_1has__pid0__allowable_error.html", null ],
        [ "has_pid0_allowableError< T, decltype((void) T::pid0_allowableError, void())>", "structargos__lib_1_1talonsrx__config_1_1has__pid0__allowable_error_3_01_t_00_01decltype_07_07voi5493ef1e2db98309090f19c7439edbd9.html", null ],
        [ "has_pid0_iZone", "structargos__lib_1_1talonsrx__config_1_1has__pid0__i_zone.html", null ],
        [ "has_pid0_iZone< T, decltype((void) T::pid0_iZone, void())>", "structargos__lib_1_1talonsrx__config_1_1has__pid0__i_zone_3_01_t_00_01decltype_07_07void_08_01_tbf902fef88b68d24b562269713314f68.html", null ],
        [ "has_pid0_kD", "structargos__lib_1_1talonsrx__config_1_1has__pid0__k_d.html", null ],
        [ "has_pid0_kD< T, decltype((void) T::pid0_kD, void())>", "structargos__lib_1_1talonsrx__config_1_1has__pid0__k_d_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_d_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_kF", "structargos__lib_1_1talonsrx__config_1_1has__pid0__k_f.html", null ],
        [ "has_pid0_kF< T, decltype((void) T::pid0_kF, void())>", "structargos__lib_1_1talonsrx__config_1_1has__pid0__k_f_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_f_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_kI", "structargos__lib_1_1talonsrx__config_1_1has__pid0__k_i.html", null ],
        [ "has_pid0_kI< T, decltype((void) T::pid0_kI, void())>", "structargos__lib_1_1talonsrx__config_1_1has__pid0__k_i_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_i_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_kP", "structargos__lib_1_1talonsrx__config_1_1has__pid0__k_p.html", null ],
        [ "has_pid0_kP< T, decltype((void) T::pid0_kP, void())>", "structargos__lib_1_1talonsrx__config_1_1has__pid0__k_p_3_01_t_00_01decltype_07_07void_08_01_t_1_1pid0__k_p_00_01void_07_08_08_4.html", null ],
        [ "has_pid0_selectedSensor", "structargos__lib_1_1talonsrx__config_1_1has__pid0__selected_sensor.html", null ],
        [ "has_pid0_selectedSensor< T, decltype((void) T::pid0_selectedSensor, void())>", "structargos__lib_1_1talonsrx__config_1_1has__pid0__selected_sensor_3_01_t_00_01decltype_07_07voi5aefa1e6b6d6329fd07217c1e420d9f5.html", null ],
        [ "has_remoteFilter0_addr", "structargos__lib_1_1talonsrx__config_1_1has__remote_filter0__addr.html", null ],
        [ "has_remoteFilter0_addr< T, decltype((void) T::remoteFilter0_addr, void())>", "structargos__lib_1_1talonsrx__config_1_1has__remote_filter0__addr_3_01_t_00_01decltype_07_07void7db44708bee280e33b8eebdcc1e2d0a9.html", null ],
        [ "has_remoteFilter0_type", "structargos__lib_1_1talonsrx__config_1_1has__remote_filter0__type.html", null ],
        [ "has_remoteFilter0_type< T, decltype((void) T::remoteFilter0_type, void())>", "structargos__lib_1_1talonsrx__config_1_1has__remote_filter0__type_3_01_t_00_01decltype_07_07void460837f07a001187eab62e537910f372.html", null ],
        [ "has_reverseLimitSwitchNormal", "structargos__lib_1_1talonsrx__config_1_1has__reverse_limit_switch_normal.html", null ],
        [ "has_reverseLimitSwitchNormal< T, decltype((void) T::reverseLimitSwitchNormal, void())>", "structargos__lib_1_1talonsrx__config_1_1has__reverse_limit_switch_normal_3_01_t_00_01decltype_078acbc695f39cf5401db2a28570ba2d19.html", null ],
        [ "has_reverseLimitSwitchSource", "structargos__lib_1_1talonsrx__config_1_1has__reverse_limit_switch_source.html", null ],
        [ "has_reverseLimitSwitchSource< T, decltype((void) T::reverseLimitSwitchSource, void())>", "structargos__lib_1_1talonsrx__config_1_1has__reverse_limit_switch_source_3_01_t_00_01decltype_07c0d43d8da92ece58defcd8f6d348606e.html", null ],
        [ "has_sensorPhase", "structargos__lib_1_1talonsrx__config_1_1has__sensor_phase.html", null ],
        [ "has_sensorPhase< T, decltype((void) T::sensorPhase, void())>", "structargos__lib_1_1talonsrx__config_1_1has__sensor_phase_3_01_t_00_01decltype_07_07void_08_01_t4c158a1c96fd2bf7c6dfcb735c6e0d25.html", null ],
        [ "has_statusFrameMotorMode", "structargos__lib_1_1talonsrx__config_1_1has__status_frame_motor_mode.html", null ],
        [ "has_statusFrameMotorMode< T, decltype((void) T::statusFrameMotorMode, void())>", "structargos__lib_1_1talonsrx__config_1_1has__status_frame_motor_mode_3_01_t_00_01decltype_07_07v17e9f7765ec4fa83077c39d6a7c9002a.html", null ],
        [ "has_voltCompSat", "structargos__lib_1_1talonsrx__config_1_1has__volt_comp_sat.html", null ],
        [ "has_voltCompSat< T, decltype((void) T::voltCompSat, void())>", "structargos__lib_1_1talonsrx__config_1_1has__volt_comp_sat_3_01_t_00_01decltype_07_07void_08_01_cc69726398d3e38e7dec19acb5bda9dc.html", null ]
      ] ],
      [ "ArgosColor", "structargos__lib_1_1_argos_color.html", "structargos__lib_1_1_argos_color" ],
      [ "ArgosLogger", "classargos__lib_1_1_argos_logger.html", "classargos__lib_1_1_argos_logger" ],
      [ "CANAddress", "structargos__lib_1_1_c_a_n_address.html", "structargos__lib_1_1_c_a_n_address" ],
      [ "ClosedLoopSensorConversions", "structargos__lib_1_1_closed_loop_sensor_conversions.html", "structargos__lib_1_1_closed_loop_sensor_conversions" ],
      [ "Debouncer", "classargos__lib_1_1_debouncer.html", "classargos__lib_1_1_debouncer" ],
      [ "DebounceSettings", "structargos__lib_1_1_debounce_settings.html", "structargos__lib_1_1_debounce_settings" ],
      [ "EdgeDetector", "classargos__lib_1_1_edge_detector.html", "classargos__lib_1_1_edge_detector" ],
      [ "FSHomingStorage", "classargos__lib_1_1_f_s_homing_storage.html", "classargos__lib_1_1_f_s_homing_storage" ],
      [ "GenericDebouncer", "classargos__lib_1_1_generic_debouncer.html", "classargos__lib_1_1_generic_debouncer" ],
      [ "HomingStorageInterface", "classargos__lib_1_1_homing_storage_interface.html", "classargos__lib_1_1_homing_storage_interface" ],
      [ "HysteresisFilter", "classargos__lib_1_1_hysteresis_filter.html", "classargos__lib_1_1_hysteresis_filter" ],
      [ "InterpMapPoint", "structargos__lib_1_1_interp_map_point.html", "structargos__lib_1_1_interp_map_point" ],
      [ "InterpolationMap", "classargos__lib_1_1_interpolation_map.html", "classargos__lib_1_1_interpolation_map" ],
      [ "LEDState", "structargos__lib_1_1_l_e_d_state.html", "structargos__lib_1_1_l_e_d_state" ],
      [ "LEDSubsystem", "classargos__lib_1_1_l_e_d_subsystem.html", "classargos__lib_1_1_l_e_d_subsystem" ],
      [ "NTMotorPIDTuner", "classargos__lib_1_1_n_t_motor_p_i_d_tuner.html", "classargos__lib_1_1_n_t_motor_p_i_d_tuner" ],
      [ "NTSubscriber", "classargos__lib_1_1_n_t_subscriber.html", "classargos__lib_1_1_n_t_subscriber" ],
      [ "SwapControllersCommand", "classargos__lib_1_1_swap_controllers_command.html", "classargos__lib_1_1_swap_controllers_command" ],
      [ "SwappableControllersSubsystem", "classargos__lib_1_1_swappable_controllers_subsystem.html", "classargos__lib_1_1_swappable_controllers_subsystem" ],
      [ "SwerveFSHomingStorage", "classargos__lib_1_1_swerve_f_s_homing_storage.html", "classargos__lib_1_1_swerve_f_s_homing_storage" ],
      [ "SwerveHomeStorageInterface", "classargos__lib_1_1_swerve_home_storage_interface.html", "classargos__lib_1_1_swerve_home_storage_interface" ],
      [ "VibrationStatus", "structargos__lib_1_1_vibration_status.html", "structargos__lib_1_1_vibration_status" ],
      [ "XboxController", "classargos__lib_1_1_xbox_controller.html", "classargos__lib_1_1_xbox_controller" ]
    ] ],
    [ "controlLoop", "namespacecontrol_loop.html", [
      [ "comp_bot", "namespacecontrol_loop_1_1comp__bot.html", [
        [ "climber", "namespacecontrol_loop_1_1comp__bot_1_1climber.html", [
          [ "climber", "structcontrol_loop_1_1comp__bot_1_1climber_1_1climber.html", "structcontrol_loop_1_1comp__bot_1_1climber_1_1climber" ]
        ] ],
        [ "drive", "namespacecontrol_loop_1_1comp__bot_1_1drive.html", [
          [ "drive", "structcontrol_loop_1_1comp__bot_1_1drive_1_1drive.html", "structcontrol_loop_1_1comp__bot_1_1drive_1_1drive" ],
          [ "linear_follower", "structcontrol_loop_1_1comp__bot_1_1drive_1_1linear__follower.html", "structcontrol_loop_1_1comp__bot_1_1drive_1_1linear__follower" ],
          [ "rotate", "structcontrol_loop_1_1comp__bot_1_1drive_1_1rotate.html", "structcontrol_loop_1_1comp__bot_1_1drive_1_1rotate" ],
          [ "rotational_follower", "structcontrol_loop_1_1comp__bot_1_1drive_1_1rotational__follower.html", "structcontrol_loop_1_1comp__bot_1_1drive_1_1rotational__follower" ]
        ] ],
        [ "elevator", "namespacecontrol_loop_1_1comp__bot_1_1elevator.html", [
          [ "arm", "structcontrol_loop_1_1comp__bot_1_1elevator_1_1arm.html", "structcontrol_loop_1_1comp__bot_1_1elevator_1_1arm" ],
          [ "elevator", "structcontrol_loop_1_1comp__bot_1_1elevator_1_1elevator.html", "structcontrol_loop_1_1comp__bot_1_1elevator_1_1elevator" ],
          [ "wrist", "structcontrol_loop_1_1comp__bot_1_1elevator_1_1wrist.html", "structcontrol_loop_1_1comp__bot_1_1elevator_1_1wrist" ]
        ] ],
        [ "intake", "namespacecontrol_loop_1_1comp__bot_1_1intake.html", [
          [ "intake", "structcontrol_loop_1_1comp__bot_1_1intake_1_1intake.html", "structcontrol_loop_1_1comp__bot_1_1intake_1_1intake" ]
        ] ]
      ] ]
    ] ],
    [ "encoder_conf", "namespaceencoder__conf.html", [
      [ "comp_bot", "namespaceencoder__conf_1_1comp__bot.html", [
        [ "drive", "namespaceencoder__conf_1_1comp__bot_1_1drive.html", [
          [ "genericTurn", "structencoder__conf_1_1comp__bot_1_1drive_1_1generic_turn.html", "structencoder__conf_1_1comp__bot_1_1drive_1_1generic_turn" ]
        ] ],
        [ "elevator", "namespaceencoder__conf_1_1comp__bot_1_1elevator.html", [
          [ "wrist", "structencoder__conf_1_1comp__bot_1_1elevator_1_1wrist.html", "structencoder__conf_1_1comp__bot_1_1elevator_1_1wrist" ]
        ] ]
      ] ]
    ] ],
    [ "field_points", "namespacefield__points.html", [
      [ "AprilTag", "structfield__points_1_1_april_tag.html", "structfield__points_1_1_april_tag" ]
    ] ],
    [ "LimelightHelpers", "namespace_limelight_helpers.html", [
      [ "BarcodeResultClass", "class_limelight_helpers_1_1_barcode_result_class.html", "class_limelight_helpers_1_1_barcode_result_class" ],
      [ "ClassificationResultClass", "class_limelight_helpers_1_1_classification_result_class.html", "class_limelight_helpers_1_1_classification_result_class" ],
      [ "DetectionResultClass", "class_limelight_helpers_1_1_detection_result_class.html", "class_limelight_helpers_1_1_detection_result_class" ],
      [ "FiducialResultClass", "class_limelight_helpers_1_1_fiducial_result_class.html", "class_limelight_helpers_1_1_fiducial_result_class" ],
      [ "IMUData", "class_limelight_helpers_1_1_i_m_u_data.html", "class_limelight_helpers_1_1_i_m_u_data" ],
      [ "LimelightResultsClass", "class_limelight_helpers_1_1_limelight_results_class.html", "class_limelight_helpers_1_1_limelight_results_class" ],
      [ "PoseEstimate", "class_limelight_helpers_1_1_pose_estimate.html", "class_limelight_helpers_1_1_pose_estimate" ],
      [ "RawFiducial", "class_limelight_helpers_1_1_raw_fiducial.html", "class_limelight_helpers_1_1_raw_fiducial" ],
      [ "RetroreflectiveResultClass", "class_limelight_helpers_1_1_retroreflective_result_class.html", null ],
      [ "SingleTargetingResultClass", "class_limelight_helpers_1_1_single_targeting_result_class.html", "class_limelight_helpers_1_1_single_targeting_result_class" ],
      [ "VisionResultsClass", "class_limelight_helpers_1_1_vision_results_class.html", "class_limelight_helpers_1_1_vision_results_class" ]
    ] ],
    [ "motorConfig", "namespacemotor_config.html", [
      [ "comp_bot", "namespacemotor_config_1_1comp__bot.html", [
        [ "climber", "namespacemotor_config_1_1comp__bot_1_1climber.html", [
          [ "climberPrimary", "structmotor_config_1_1comp__bot_1_1climber_1_1climber_primary.html", "structmotor_config_1_1comp__bot_1_1climber_1_1climber_primary" ],
          [ "climberSecondary", "structmotor_config_1_1comp__bot_1_1climber_1_1climber_secondary.html", "structmotor_config_1_1comp__bot_1_1climber_1_1climber_secondary" ]
        ] ],
        [ "drive", "namespacemotor_config_1_1comp__bot_1_1drive.html", [
          [ "backLeftTurn", "structmotor_config_1_1comp__bot_1_1drive_1_1back_left_turn.html", "structmotor_config_1_1comp__bot_1_1drive_1_1back_left_turn" ],
          [ "backRightTurn", "structmotor_config_1_1comp__bot_1_1drive_1_1back_right_turn.html", "structmotor_config_1_1comp__bot_1_1drive_1_1back_right_turn" ],
          [ "frontLeftTurn", "structmotor_config_1_1comp__bot_1_1drive_1_1front_left_turn.html", "structmotor_config_1_1comp__bot_1_1drive_1_1front_left_turn" ],
          [ "frontRightTurn", "structmotor_config_1_1comp__bot_1_1drive_1_1front_right_turn.html", "structmotor_config_1_1comp__bot_1_1drive_1_1front_right_turn" ],
          [ "genericDrive", "structmotor_config_1_1comp__bot_1_1drive_1_1generic_drive.html", "structmotor_config_1_1comp__bot_1_1drive_1_1generic_drive" ]
        ] ],
        [ "elevator", "namespacemotor_config_1_1comp__bot_1_1elevator.html", [
          [ "arm", "structmotor_config_1_1comp__bot_1_1elevator_1_1arm.html", "structmotor_config_1_1comp__bot_1_1elevator_1_1arm" ],
          [ "primaryElevator", "structmotor_config_1_1comp__bot_1_1elevator_1_1primary_elevator.html", "structmotor_config_1_1comp__bot_1_1elevator_1_1primary_elevator" ],
          [ "secondaryElevator", "structmotor_config_1_1comp__bot_1_1elevator_1_1secondary_elevator.html", "structmotor_config_1_1comp__bot_1_1elevator_1_1secondary_elevator" ],
          [ "wrist", "structmotor_config_1_1comp__bot_1_1elevator_1_1wrist.html", "structmotor_config_1_1comp__bot_1_1elevator_1_1wrist" ]
        ] ],
        [ "intake", "namespacemotor_config_1_1comp__bot_1_1intake.html", [
          [ "intake", "structmotor_config_1_1comp__bot_1_1intake_1_1intake.html", "structmotor_config_1_1comp__bot_1_1intake_1_1intake" ]
        ] ]
      ] ]
    ] ],
    [ "ActiveVisionTarget", "struct_active_vision_target.html", "struct_active_vision_target" ],
    [ "AutonomousChoreoTest", "class_autonomous_choreo_test.html", "class_autonomous_choreo_test" ],
    [ "AutonomousCommand", "class_autonomous_command.html", "class_autonomous_command" ],
    [ "AutonomousForward", "class_autonomous_forward.html", "class_autonomous_forward" ],
    [ "AutonomousL1FE", "class_autonomous_l1_f_e.html", "class_autonomous_l1_f_e" ],
    [ "AutonomousL1GH", "class_autonomous_l1_g_h.html", "class_autonomous_l1_g_h" ],
    [ "AutonomousL1IJ", "class_autonomous_l1_i_j.html", "class_autonomous_l1_i_j" ],
    [ "AutonomousL1JL4L", "class_autonomous_l1_j_l4_l.html", "class_autonomous_l1_j_l4_l" ],
    [ "AutonomousL1L4EDC", "class_autonomous_l1_l4_e_d_c.html", "class_autonomous_l1_l4_e_d_c" ],
    [ "AutonomousL1L4JKL", "class_autonomous_l1_l4_j_k_l.html", "class_autonomous_l1_l4_j_k_l" ],
    [ "AutonomousL4EDC", "class_autonomous_l4_e_d_c.html", "class_autonomous_l4_e_d_c" ],
    [ "AutonomousL4G", "class_autonomous_l4_g.html", "class_autonomous_l4_g" ],
    [ "AutonomousL4GAlgae", "class_autonomous_l4_g_algae.html", "class_autonomous_l4_g_algae" ],
    [ "AutonomousL4GAlgaeVision", "class_autonomous_l4_g_algae_vision.html", "class_autonomous_l4_g_algae_vision" ],
    [ "AutonomousL4JKL", "class_autonomous_l4_j_k_l.html", "class_autonomous_l4_j_k_l" ],
    [ "AutonomousNothing", "class_autonomous_nothing.html", "class_autonomous_nothing" ],
    [ "AutoSelector", "class_auto_selector.html", "class_auto_selector" ],
    [ "CameraInterface", "class_camera_interface.html", "class_camera_interface" ],
    [ "ClimbCommand", "class_climb_command.html", "class_climb_command" ],
    [ "ClimberSubsystem", "class_climber_subsystem.html", "class_climber_subsystem" ],
    [ "DriveByTimeCommand", "class_drive_by_time_command.html", "class_drive_by_time_command" ],
    [ "DriveByTimeVisionCommand", "class_drive_by_time_vision_command.html", "class_drive_by_time_vision_command" ],
    [ "DriveChoreo", "class_drive_choreo.html", "class_drive_choreo" ],
    [ "ElevatorSubsystem", "class_elevator_subsystem.html", "class_elevator_subsystem" ],
    [ "GoToPositionCommand", "class_go_to_position_command.html", "class_go_to_position_command" ],
    [ "InitializeOdometryCommand", "class_initialize_odometry_command.html", "class_initialize_odometry_command" ],
    [ "IntakeSubsystem", "class_intake_subsystem.html", "class_intake_subsystem" ],
    [ "L1CoralPlacementCommand", "class_l1_coral_placement_command.html", "class_l1_coral_placement_command" ],
    [ "L4CoralPlacementCommand", "class_l4_coral_placement_command.html", "class_l4_coral_placement_command" ],
    [ "LimelightTarget", "class_limelight_target.html", "class_limelight_target" ],
    [ "MiddleCoralPlacementCommand", "class_middle_coral_placement_command.html", "class_middle_coral_placement_command" ],
    [ "OperatorController", "class_operator_controller.html", "class_operator_controller" ],
    [ "Position", "struct_position.html", "struct_position" ],
    [ "Robot", "class_robot.html", "class_robot" ],
    [ "RobotContainer", "class_robot_container.html", "class_robot_container" ],
    [ "SimpleLedSubsystem", "class_simple_led_subsystem.html", "class_simple_led_subsystem" ],
    [ "SwerveDriveSubsystem", "class_swerve_drive_subsystem.html", "class_swerve_drive_subsystem" ],
    [ "SwerveModule", "class_swerve_module.html", "class_swerve_module" ],
    [ "unitlessChassisSpeeds", "structunitless_chassis_speeds.html", "structunitless_chassis_speeds" ],
    [ "VisionSubsystem", "class_vision_subsystem.html", "class_vision_subsystem" ]
];