# This is a basic workflow to build robot code.

name: Format

# Controls when the action will run. Triggers the workflow on push or pull request
on:
  pull_request:

jobs:
  wpiformat:
    name: "wpiformat"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0' # Make sure main is available
          token: ${{ secrets.FORMAT_REPO_ACCESS_TOKEN }} # Ensure formatting commits trigger additional formatting check for PR job requirements
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Create main branch
        # This is only necessary because wpiformat refuses to run without a main branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: git branch main
      - uses: pre-commit/action@v3.0.1
        id: formatCheck
        continue-on-error: true
        with:
          extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
      - name: 'Commit formatting changes'
        id: commit-changes
        if: steps.formatCheck.outcome != 'success'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Apply automatic formatting"
          skip_dirty_check: true
          skip_fetch: true
          skip_checkout: true
      - name: 'Verify formatting'
        if: steps.formatCheck.outcome != 'success'
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --from-ref ${{ github.event.pull_request.base.sha }} --to-ref ${{ github.event.pull_request.head.sha }}
      - name: 'Update commit status'
        if: steps.commit-changes.outputs.changes_detected == 'true'
        uses: myrotvorets/set-commit-status-action@v2.0.1
        with:
          status: ${{ job.status }}
          sha: ${{ steps.commit-changes.outputs.commit_hash }}
